wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1660835099.968446
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.7.12
      5: 0.13.1
      8:
      - 5
dataset_config:
  desc: null
  value:
    apply_one_hot: true
    apply_resize: false
    batch_size: 128
    channels: 3
    dataset_name: bloodmnist
    do_cache: false
    image_height: 28
    image_width: 28
    num_classes: 10
lr_config:
  desc: null
  value:
    cosine_decay_steps: 1000
    exp_decay_rate: 0.96
    exp_decay_steps: 1000
    exp_is_staircase: true
    init_lr_rate: 0.001
seed:
  desc: null
  value: 0
train_config:
  desc: null
  value:
    backbone: resnet50
    dropout_rate: 0.5
    early_patience: 6
    epochs: 3
    loss: categorical_crossentropy
    model_img_channels: 3
    model_img_height: 28
    model_img_width: 28
    optimizer: adam
    post_gap_dropout: false
    resume: false
    rlrp_factor: 0.2
    rlrp_patience: 3
    sgd_momentum: 0.9
    use_augmentations: false
    use_class_weights: false
    use_lr_scheduler: false
    use_pretrained_weights: true
wandb_config:
  desc: null
  value:
    log_validation_table: false
    project: medmnist2D
